public enum Event
{
    ProductionCompleted,
    ProductionHalted,
    ProductionMissingItems,
    ItemsTransferred,
    ResourceChanged,
    Sundown,
    DayStarted,
    SpawnRat,
    QuotaUpdated,
    ClockTick,
    StartQte,
    QteStarted,
    QteCompleted,
    RatPickedUp,
    RatReleased,
    HazardDisruption,
    SetDisruptFacilityInRange,
    SpawnHazard
}